// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNXtgz0_CJH5JAn-_MFWSmwgo32O5GYOY',
    appId: '1:500762124002:web:81bb04288681af993688bb',
    messagingSenderId: '500762124002',
    projectId: 'service-ccb5b',
    authDomain: 'service-ccb5b.firebaseapp.com',
    storageBucket: 'service-ccb5b.appspot.com',
    measurementId: 'G-HN5F2K598V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXgItul_wCkf1qGfQEtT49sIzDceNVhg',
    appId: '1:500762124002:android:8b99ad26cefac49a3688bb',
    messagingSenderId: '500762124002',
    projectId: 'service-ccb5b',
    storageBucket: 'service-ccb5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFtI17TznFMGvpzHeJAiT3kZO1JpLHUk',
    appId: '1:500762124002:ios:cd67aeb0306c7a803688bb',
    messagingSenderId: '500762124002',
    projectId: 'service-ccb5b',
    storageBucket: 'service-ccb5b.appspot.com',
    iosClientId: '500762124002-d3lrbkiec1kvgpgu6gor7jdvj74qv0v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ranking',
  );
}
